# Generated by Django 4.1.3 on 2022-11-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cwiczenia', '0002_partie'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
    ]
