# Generated by Django 4.1.3 on 2022-11-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cwiczenia', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
