# Generated by Django 4.1.3 on 2022-11-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cwiczenia', '0004_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cwiczenia',
            options={'verbose_name': 'Cwiczenie', 'verbose_name_plural': 'Cwiczenia'},
        ),
        migrations.AlterModelOptions(
            name='partie',
            options={'verbose_name': 'Partia', 'verbose_name_plural': 'Partie'},
        ),
        migrations.AddField(
            model_name='cwiczenia',
            name='partia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cwiczenia.partie'),
        ),
    ]
