# Generated by Django 4.1.3 on 2022-12-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cwiczenia', '0005_alter_cwiczenia_options_alter_partie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwiczenia',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
