# Generated by Django 4.1.3 on 2022-12-20 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cwiczenia', '0006_cwiczenia_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekordy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Data wpisu')),
                ('lawa', models.FloatField()),
                ('martwy', models.FloatField()),
                ('przysiad', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uzytkownik')),
            ],
            options={
                'verbose_name': 'Rekord',
                'verbose_name_plural': 'Rekordy',
            },
        ),
    ]
