# Generated by Django 4.1.3 on 2022-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cwiczenia', '0008_rename_lawa_rekordy_rekord_remove_rekordy_martwy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rekordy',
            name='create_date',
        ),
        migrations.AddField(
            model_name='rekordy',
            name='nazwa',
            field=models.CharField(default='rekord', max_length=100),
        ),
    ]
