# Generated by Django 4.1.3 on 2022-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cwiczenia', '0011_plany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cwiczenia',
            name='img',
        ),
        migrations.AddField(
            model_name='cwiczenia',
            name='film',
            field=models.TextField(blank=True),
        ),
    ]
